### ISSUE TITLE
Release materials for 0.2.0

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#274]
Set of materials for the 0.2.0 release:

- [x] Release blog explaining model parts and Dev mode [Gorkem]
- [ ] #308
- [x] #169 -- updated for model parts [Rajat]
- [x] #307
- [x] Update readme with dev mode and fine-tuning / RAG capabilities [Brad]
- [x] Add a comment on [this post](https://dev.to/bmicklea/comment/2eio7) to redirect to the new blog

**Comment by bmicklea** [comment]
We can follow on this release with addition of LoRA adapters to dev mode for a later release.

**Comment by bmicklea** [comment]
Closing as complete - the video will be done with the updated Dev UX
